// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package mikegpl.sr.grpc;

public interface ConvertersStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConvertersState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .CurrencyConverter converter = 1;</code>
   */
  java.util.List<mikegpl.sr.grpc.CurrencyConverter> 
      getConverterList();
  /**
   * <code>repeated .CurrencyConverter converter = 1;</code>
   */
  mikegpl.sr.grpc.CurrencyConverter getConverter(int index);
  /**
   * <code>repeated .CurrencyConverter converter = 1;</code>
   */
  int getConverterCount();
  /**
   * <code>repeated .CurrencyConverter converter = 1;</code>
   */
  java.util.List<? extends mikegpl.sr.grpc.CurrencyConverterOrBuilder> 
      getConverterOrBuilderList();
  /**
   * <code>repeated .CurrencyConverter converter = 1;</code>
   */
  mikegpl.sr.grpc.CurrencyConverterOrBuilder getConverterOrBuilder(
      int index);
}
