// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package mikegpl.sr.grpc;

public interface CurrencyConverterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CurrencyConverter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Currency name = 1;</code>
   */
  int getNameValue();
  /**
   * <code>.Currency name = 1;</code>
   */
  mikegpl.sr.grpc.Currency getName();

  /**
   * <code>double rate = 2;</code>
   */
  double getRate();
}
