// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package mikegpl.sr.grpc;

public final class CurrencyProto {
  private CurrencyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyConverter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyConverter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CurrencyStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CurrencyStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StreamConverterStateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StreamConverterStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertersState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertersState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016currency.proto\":\n\021CurrencyConverter\022\027\n" +
      "\004name\030\001 \001(\0162\t.Currency\022\014\n\004rate\030\002 \001(\001\"3\n\024" +
      "CurrencyStateRequest\022\033\n\010currency\030\001 \003(\0162\t" +
      ".Currency\":\n\033StreamConverterStateRequest" +
      "\022\033\n\010currency\030\001 \003(\0162\t.Currency\"8\n\017Convert" +
      "ersState\022%\n\tconverter\030\001 \003(\0132\022.CurrencyCo" +
      "nverter*.\n\010Currency\022\007\n\003PLN\020\000\022\007\n\003USD\020\001\022\007\n" +
      "\003EUR\020\002\022\007\n\003VEF\020\0032\233\001\n\017CurrencyService\022>\n\021C" +
      "urrentConverters\022\025.CurrencyStateRequest\032" +
      "\020.ConvertersState\"\000\022H\n\020StreamConverters\022" +
      "\034.StreamConverterStateRequest\032\022.Currency" +
      "Converter\"\0000\001B\"\n\017mikegpl.sr.grpcB\rCurren" +
      "cyProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CurrencyConverter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CurrencyConverter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyConverter_descriptor,
        new java.lang.String[] { "Name", "Rate", });
    internal_static_CurrencyStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CurrencyStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CurrencyStateRequest_descriptor,
        new java.lang.String[] { "Currency", });
    internal_static_StreamConverterStateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StreamConverterStateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StreamConverterStateRequest_descriptor,
        new java.lang.String[] { "Currency", });
    internal_static_ConvertersState_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ConvertersState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertersState_descriptor,
        new java.lang.String[] { "Converter", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
