// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package mikegpl.sr.grpc;

/**
 * Protobuf type {@code StreamConverterStateRequest}
 */
public  final class StreamConverterStateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StreamConverterStateRequest)
    StreamConverterStateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StreamConverterStateRequest.newBuilder() to construct.
  private StreamConverterStateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StreamConverterStateRequest() {
    currency_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StreamConverterStateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              currency_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            currency_.add(rawValue);
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                currency_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              currency_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        currency_ = java.util.Collections.unmodifiableList(currency_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mikegpl.sr.grpc.CurrencyProto.internal_static_StreamConverterStateRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mikegpl.sr.grpc.CurrencyProto.internal_static_StreamConverterStateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mikegpl.sr.grpc.StreamConverterStateRequest.class, mikegpl.sr.grpc.StreamConverterStateRequest.Builder.class);
  }

  public static final int CURRENCY_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> currency_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, mikegpl.sr.grpc.Currency> currency_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, mikegpl.sr.grpc.Currency>() {
            public mikegpl.sr.grpc.Currency convert(java.lang.Integer from) {
              mikegpl.sr.grpc.Currency result = mikegpl.sr.grpc.Currency.valueOf(from);
              return result == null ? mikegpl.sr.grpc.Currency.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  public java.util.List<mikegpl.sr.grpc.Currency> getCurrencyList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, mikegpl.sr.grpc.Currency>(currency_, currency_converter_);
  }
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  public int getCurrencyCount() {
    return currency_.size();
  }
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  public mikegpl.sr.grpc.Currency getCurrency(int index) {
    return currency_converter_.convert(currency_.get(index));
  }
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  public java.util.List<java.lang.Integer>
  getCurrencyValueList() {
    return currency_;
  }
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  public int getCurrencyValue(int index) {
    return currency_.get(index);
  }
  private int currencyMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getCurrencyList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(currencyMemoizedSerializedSize);
    }
    for (int i = 0; i < currency_.size(); i++) {
      output.writeEnumNoTag(currency_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < currency_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(currency_.get(i));
      }
      size += dataSize;
      if (!getCurrencyList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }currencyMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mikegpl.sr.grpc.StreamConverterStateRequest)) {
      return super.equals(obj);
    }
    mikegpl.sr.grpc.StreamConverterStateRequest other = (mikegpl.sr.grpc.StreamConverterStateRequest) obj;

    boolean result = true;
    result = result && currency_.equals(other.currency_);
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCurrencyCount() > 0) {
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + currency_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mikegpl.sr.grpc.StreamConverterStateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mikegpl.sr.grpc.StreamConverterStateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StreamConverterStateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StreamConverterStateRequest)
      mikegpl.sr.grpc.StreamConverterStateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mikegpl.sr.grpc.CurrencyProto.internal_static_StreamConverterStateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mikegpl.sr.grpc.CurrencyProto.internal_static_StreamConverterStateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mikegpl.sr.grpc.StreamConverterStateRequest.class, mikegpl.sr.grpc.StreamConverterStateRequest.Builder.class);
    }

    // Construct using mikegpl.sr.grpc.StreamConverterStateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      currency_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mikegpl.sr.grpc.CurrencyProto.internal_static_StreamConverterStateRequest_descriptor;
    }

    public mikegpl.sr.grpc.StreamConverterStateRequest getDefaultInstanceForType() {
      return mikegpl.sr.grpc.StreamConverterStateRequest.getDefaultInstance();
    }

    public mikegpl.sr.grpc.StreamConverterStateRequest build() {
      mikegpl.sr.grpc.StreamConverterStateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public mikegpl.sr.grpc.StreamConverterStateRequest buildPartial() {
      mikegpl.sr.grpc.StreamConverterStateRequest result = new mikegpl.sr.grpc.StreamConverterStateRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        currency_ = java.util.Collections.unmodifiableList(currency_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.currency_ = currency_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mikegpl.sr.grpc.StreamConverterStateRequest) {
        return mergeFrom((mikegpl.sr.grpc.StreamConverterStateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mikegpl.sr.grpc.StreamConverterStateRequest other) {
      if (other == mikegpl.sr.grpc.StreamConverterStateRequest.getDefaultInstance()) return this;
      if (!other.currency_.isEmpty()) {
        if (currency_.isEmpty()) {
          currency_ = other.currency_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCurrencyIsMutable();
          currency_.addAll(other.currency_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mikegpl.sr.grpc.StreamConverterStateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mikegpl.sr.grpc.StreamConverterStateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> currency_ =
      java.util.Collections.emptyList();
    private void ensureCurrencyIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        currency_ = new java.util.ArrayList<java.lang.Integer>(currency_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public java.util.List<mikegpl.sr.grpc.Currency> getCurrencyList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, mikegpl.sr.grpc.Currency>(currency_, currency_converter_);
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public int getCurrencyCount() {
      return currency_.size();
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public mikegpl.sr.grpc.Currency getCurrency(int index) {
      return currency_converter_.convert(currency_.get(index));
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder setCurrency(
        int index, mikegpl.sr.grpc.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCurrencyIsMutable();
      currency_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder addCurrency(mikegpl.sr.grpc.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCurrencyIsMutable();
      currency_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder addAllCurrency(
        java.lang.Iterable<? extends mikegpl.sr.grpc.Currency> values) {
      ensureCurrencyIsMutable();
      for (mikegpl.sr.grpc.Currency value : values) {
        currency_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder clearCurrency() {
      currency_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public java.util.List<java.lang.Integer>
    getCurrencyValueList() {
      return java.util.Collections.unmodifiableList(currency_);
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public int getCurrencyValue(int index) {
      return currency_.get(index);
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder setCurrencyValue(
        int index, int value) {
      ensureCurrencyIsMutable();
      currency_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder addCurrencyValue(int value) {
      ensureCurrencyIsMutable();
      currency_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .Currency currency = 1;</code>
     */
    public Builder addAllCurrencyValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureCurrencyIsMutable();
      for (int value : values) {
        currency_.add(value);
      }
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StreamConverterStateRequest)
  }

  // @@protoc_insertion_point(class_scope:StreamConverterStateRequest)
  private static final mikegpl.sr.grpc.StreamConverterStateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mikegpl.sr.grpc.StreamConverterStateRequest();
  }

  public static mikegpl.sr.grpc.StreamConverterStateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StreamConverterStateRequest>
      PARSER = new com.google.protobuf.AbstractParser<StreamConverterStateRequest>() {
    public StreamConverterStateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StreamConverterStateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StreamConverterStateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StreamConverterStateRequest> getParserForType() {
    return PARSER;
  }

  public mikegpl.sr.grpc.StreamConverterStateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

