// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: currency.proto

package mikegpl.sr.grpc;

public interface StreamConverterStateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StreamConverterStateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  java.util.List<mikegpl.sr.grpc.Currency> getCurrencyList();
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  int getCurrencyCount();
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  mikegpl.sr.grpc.Currency getCurrency(int index);
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getCurrencyValueList();
  /**
   * <code>repeated .Currency currency = 1;</code>
   */
  int getCurrencyValue(int index);
}
